version: "3"

services:
    cloudmapper:
        build:
            context: .
        image: cloudmapper
        container_name: cloudmapper
        env_file: .env
        volumes:
            #- ./account-data:/opt/cloudmapper/account-data
            - ./config.json:/opt/cloudmapper/config.json
            #- ./web:/opt/cloudmapper/web
        ports:
            - ${EXTERNAL_PORT}:8000
        # TODO: switch to environment variables instead loading the .env manually
        # environment:
        #     - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
        #     - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
        #     - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
        #     - ACCOUNT=${ACCOUNT}
        #     - DEMO_MODE=${DEMO_MODE}
        #restart: always
